const advanceActionTypes = {
  SET_VALUE: 'SET_VALUE',
  IS_FETCHING_ENTITY_DETAILS: 'IS_FETCHING_ENTITY_DETAILS',
  SET_ENTITY_DETAILS: 'SET_ENTITY_DETAILS',
  SHOULD_SHOW_ITEMS: 'SHOULD_SHOW_ITEMS',
  IS_FETCHING_ITEM_DATA: 'IS_FETCHING_ITEM_DATA',
  SET_ITEM_DATA: 'SET_ITEM_DATA',
};

export default advanceActionTypes;
