export default {
  accessor: {
    lineItemId: 'lineItemId',
    categoryDesc: 'categoryDesc',
    subCategoryDesc: 'subCategoryDesc',
    uom: 'uom',
    price: 'price',
    sgst: 'sgst',
    cgst: 'cgst',
    tax: 'tax',
    netPrice: 'netPrice',
    totalAmount: 'totalAmount',
    quantity: 'quantity',
    itemDescription: 'itemDescription',
    comments: 'comments',
  },
  ids: {
    entityName: 'entityName',
    viewName: 'viewName',
    poFromLabel: 'poFromLabel',
    requisitionNo: 'requisitionNo',
    workflowName: 'workflowName',
    supplierName: 'supplierName',
    currencyCode: 'currencyCode',
    billingAddressId: 'billingAddressId',
    shippingAddressId: 'shippingAddressId',
    poTotalNetPrice: 'poTotalNetPrice',
    poTotalTax: 'poTotalTax',
    totalAmount: 'totalAmount',
    advancePayment: 'advancePayment',
    terms: 'terms',
    paymentTerms: 'paymentTerms',
    comments: 'comments',
    contactNo: 'contactNo',
    tinNo: 'tinNo',
    vatNo: 'vatNo',
    deliveryAddress: 'deliveryAddress',
    addressInput: 'addressInput',
  },
  labels: {
    rupees: '₹',
    Entity: 'Entity',
    View: 'View',
    Type: 'Type',
    PORequestNo: 'PO Request #',
    Workflow: 'Workflow',
    Supplier: 'Supplier',
    Currency: 'Currency',
    billingAddress: 'Billing Address',
    shipToAddress: 'Ship To Address',
    totalNetPrice: 'Total NetPrice',
    totalTax: 'Total Tax',
    grandTotal: 'Grand Total',
    advancePayment: 'Advance Payment %',
    terms: 'Terms',
    paymentTerms: 'Payment Terms',
    comments: 'Comments',
    lineItemId: 'Item #',
    category: 'Category',
    subCategory: 'Sub Category',
    uom: 'UOM',
    price: 'Price',
    sgst: 'SGST %',
    cgst: 'CGST %',
    tax: 'Tax',
    netPrice: 'Net Price',
    totalAmount: 'Total',
    quantity: 'Qty',
    itemDescription: 'Item',
    contactNo: 'Contact No',
    tinNo: 'GSTIN',
    vatNo: 'VAT #',
    deliveryAddress: 'Delivery Address',
    addressInput: 'Enter Shipping Address',
  },
  names: {
    entityName: 'entityName',
    viewName: 'viewName',
    poFromLabel: 'poFromLabel',
    requisitionNo: 'requisitionNo',
    workflowName: 'workflowName',
    supplierName: 'supplierName',
    currencyCode: 'currencyCode',
    billingAddressId: 'billingAddressId',
    shippingAddressId: 'shippingAddressId',
    poTotalNetPrice: 'poTotalNetPrice',
    poTotalTax: 'poTotalTax',
    totalAmount: 'totalAmount',
    advancePayment: 'advancePayment',
    terms: 'terms',
    paymentTerms: 'paymentTerms',
    comments: 'comments',
    contactNo: 'contactNo',
    tinNo: 'tinNo',
    vatNo: 'vatNo',
    deliveryAddress: 'deliveryAddress',
    addressInput: 'addressInput',
  },
  helperText: {
    billingAddress: 'Choose a billing address',
    shipToAddress: 'Choose a shipping address',
    tinNo: '(format: 00AAAAA0000A1Z0)',
  }
}